ATAM/ATAM/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),

    path('',include('tracking.urls')),
    path('user/',include('user.urls')),
    path('maintenance/',include('maintenance.urls')),


    #path('',include('tracking.urls')),
    path('tracking/',include('tracking.urls')),
    path('',include('user.urls')),
    path('inventory/',include('inventory.urls')),
    
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ATAM/inventory/urls.py
from django.urls import path
from .views import*
app_name = 'inventory'
urlpatterns = [
    path('',index,name='index'),
    path('add_asset/', add_asset ,name='add_asset'),
    path('add_asset/<int:id>', update_asset ,name='add_asset_instance'),
    path('delete_asset/<int:id>', delete_asset ,name='delete_asset'),
    path('add_tracker/', add_tracker ,name='add_tracker'),
    path('add_tracker/<int:id>', update_tracker ,name='add_tracker_instance'),
    path('delete_tracker/<int:id>', delete_tracker ,name='delete_tracker'),
    path('add_job/', add_job ,name='add_job'),
    path('add_job/<int:id>', update_job ,name='add_job_instance'),
    path('delete_job/<int:id>', delete_job ,name='delete_job'),
    
]

ATAM/inventory/models.py
from django.db import models

# Create your models here.

    

ATAM/inventory/forms.py
from django import forms
from tracking.models import Asset,Tracker,Job

class AddAssetForm(forms.ModelForm):
    class Meta:
        model = Asset
        fields= '__all__'


class AddTrackerForm(forms.ModelForm):
    class Meta:
        model = Tracker
        fields= '__all__'

class AddJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = '__all__'

ATAM/inventory/views.py
from django.shortcuts import render
from tracking.models import Asset,Tracker,Job
from .forms import AddAssetForm,AddTrackerForm,AddJobForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required()
def index(request):
    asset = Asset.objects.all()
    tracker = Tracker.objects.all()
    job = Job.objects.all()
    context = {
        'asset':asset,
        'tracker':tracker,
        'job':job,
       
    }
    
    return render(request,'inventory/index.html',context)
@login_required()
def add_asset(request):
    form = AddAssetForm()
    if request.method == 'POST':
        form = AddAssetForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/inventory/')
    else:

        context = {
            'form':form
        }
        return render(request,'inventory/add_asset.html',context)
@login_required()
def update_asset(request,id):
    asset = Asset.objects.get(id=id)
    if request.method == 'POST':
        form = AddAssetForm(request.POST,instance=asset)
        if form.is_valid():
            form.save()
            return redirect('/inventory/')


    else:
        form = AddAssetForm(instance=asset)

    return render(request, 'inventory/add_asset.html', {'form': form})    
@login_required()
def delete_asset(request,id):
    print('-------------------')
    asset_instance = Asset.objects.filter(pk=id)
    print("deleted!",asset_instance)
    asset_instance.delete()
    return redirect('/inventory/')


def add_tracker(request):
    form = AddTrackerForm()
    if request.method == 'POST':
        form = AddTrackerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/inventory/')
    else:

        context = {
            'form':form
        }
        return render(request,'inventory/add_tracker.html',context)

def update_tracker(request,id):
    tracker = Tracker.objects.get(pk=id)
    if request.method == 'POST':
        form = AddTrackerForm(request.POST,instance=tracker)
        if form.is_valid():
            form.save()
            return redirect('/inventory/')
    else:
        form = AddTrackerForm(instance=tracker)

    return render(request, 'inventory/add_tracker.html', {'form': form})    

def delete_tracker(request,id):
    tracker_instance = Tracker.objects.filter(pk=id)
    tracker_instance.delete()
    return redirect('/inventory/')


def add_job(request):
    form = AddJobForm()
    if request.method == 'POST':
        form = AddJobForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/inventory/')
    else:

        context = {
            'form':form
        }
        return render(request,'inventory/add_job.html',context)

def update_job(request,id):
    job = Job.objects.get(pk=id)
    if request.method == 'POST':
        form = AddJobForm(request.POST,instance=job)
        if form.is_valid():
            form.save()
            return redirect('/inventory/')
    else:
        form = AddJobForm(instance=job)

    return render(request, 'inventory/add_job.html', {'form': form})    

def delete_job(request,id):
    job_instance = Job.objects.filter(pk=id)
    job_instance.delete()
    return redirect('/inventory/')

ATAM/inventory/templates/inventory/add_asset.html
{% extends "tracking/layout.html" %}
{% load static %}

{% block title %}ATAM{% endblock %}

{% block body %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'tracking/css/styles.css' %}">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% load crispy_forms_tags %}  
<body>
    <h3>
        Add Asset
    </h3>
    <form method="post">
        {% csrf_token %}
        <div class="md-form form-group w-50">{{ form.asset_name|as_crispy_field }}</div>
        <div class="md-form form-group w-25">{{ form.assigned_tracker|as_crispy_field }}</div>
        <div class="md-form form-group w-50">{{ form.description|as_crispy_field }}</div>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

ATAM/inventory/templates/inventory/add_job.html
{% extends "tracking/layout.html" %}
{% load static %}

{% block title %}ATAM{% endblock %}

{% block body %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'tracking/css/styles.css' %}">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% load crispy_forms_tags %}  
<body>
    <h3>
        Add Job
    </h3>
    <form method="post">
        {% csrf_token %}
        <div class="md-form form-group w-50">{{ form.user|as_crispy_field }}</div>
        <div class="md-form form-group w-25">{{ form.tracker|as_crispy_field }}</div>
        <div class="md-form form-group w-50">{{ form.title|as_crispy_field }}</div>
        <div class="md-form form-group w-50">{{ form.origin|as_crispy_field }}</div>
        <div class="md-form form-group w-50">{{ form.destination|as_crispy_field }}</div>
        <div class="md-form form-group w-50">{{ form.description|as_crispy_field }}</div>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

ATAM/inventory/templates/inventory/add_tracker.html
{% extends "tracking/layout.html" %}
{% load static %}

{% block title %}ATAM{% endblock %}

{% block body %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'tracking/css/styles.css' %}">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% load crispy_forms_tags %}  
<body>
    <h3>
        Add Tracker
    </h3>
    <form method="post">
        {% csrf_token %}
        <div class="md-form form-group w-50">{{ form.tracker_name|as_crispy_field }}</div>
        <div class="md-form form-group w-25">{{ form.tracker|as_crispy_field }}</div>
        <div class="md-form form-group w-50">{{ form.status|as_crispy_field }}</div>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

ATAM/inventory/templates/inventory/index.html
{% extends "tracking/layout.html" %}
{% load static %}
{% block body %}
	
	
<!-- CSS only -->
<link rel="stylesheet" type="text/css" href="{% static 'tracking/css/styles.css' %}">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" 
rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
	<style>
        header
{
	font-size: 1.5em;
	color: black;
}
th
{
	font-size: 1em;
	padding: 15px;
	margin-left: 50px;
	background-color: skyblue;
}
td
{
	font-size: 1em;
	padding: 15px;
	margin-left: 10px;
}
    </style>

<div>
	<h1 style="margin-left: 30px">Inventory</h1>

	<div style="margin-top:50px;float: right;margin-right:7%">
		<a href="{% url 'inventory:add_job'  %}"><button type="submit" class="btn btn-primary" name="button">Add Job</button></a>
	
	</div>
	<table class="table table-hover">
		<header style="margin-top:50px">
			<h2 style="margin-left: 30px">Jobs</h2>
		</header>
        <thead>
			<tr style="text-align: left; background-color: skyblue;" style="margin-left: 30px">
				<th>Related User</th>
				<th>Tracker</th>
				<th>Title</th>    
				<th>Origin</th>
				<th>Destination</th>    
				<th>Description</th>
				
			<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for job in job %}
        <tr> 
            <td>{{ job.user }}</td>
            
            <td>{{ job.tracker }}</td>
            <td>{{ job.title }}</td>
            <td>{{ job.origin }}</td>
			<td>{{ job.destination }}</td>
			<td>{{ job.description }}</td>
            <td> <a href="{% url 'inventory:add_job_instance' job.id %}"><button type="submit" class="btn btn-warning btn-sm" name="button">Edit</button></a>
			<a href="{% url 'inventory:delete_job' job.id %}"><button type="submit" class="btn btn-danger btn-sm" name="button">Delete</button></a></td>
        </tr>
        {% endfor %}
	</tbody>
    </table>
	<br>
	<br>

	
	<div style="margin-top:50px;float: right;margin-right:7%">
		<a href="{% url 'inventory:add_asset'  %}"><button type="submit" class="btn btn-primary" name="button">Add Asset</button></a>
	
	</div>
	<table class="table table-hover">
		<header style="margin-top:50px">
			<h2 style="margin-left: 30px">Asset</h2>
		</header>
        <thead>
			<tr style="text-align: left; background-color: skyblue;" style="margin-left: 30px">
				<th>Asset Name</th>
				<th>Assigned Tracker</th>
				<th>Asset Description</th>    
				<th>Created At</th>
			<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for asset in asset %}
        <tr> 
            <td>{{ asset.asset_name }}</td>
            
            <td>{{ asset.assigned_tracker }}</td>
            <td>{{ asset.description }}</td>
            <td>{{ asset.created_at }}</td>
            <td> <a href="{% url 'inventory:add_asset_instance' asset.id %}"><button type="submit" class="btn btn-warning btn-sm" name="button">Edit</button></a>
			<a href="{% url 'inventory:delete_asset' asset.id %}"><button type="submit" class="btn btn-danger btn-sm" name="button">Delete</button></a></td>
        </tr>
        {% endfor %}
	</tbody>
    </table>
	<br>
	<br>

	<div style="margin-top:50px;float: right;margin-right:7%">
   
		<a href="{% url 'inventory:add_tracker'  %}"><button type="submit" class="btn btn-primary" name="button">Add Tracker</button></a>
	</div>

<table class="table table-hover">
		<header>
			<h2 style="margin-left: 30px">Trackers</h2>
		</header>
        <thead>
			<tr style="text-align: left; background-color: skyblue;" style="margin-left: 30px">
			<th>Tracker Name</th>
			<th>Related Asset</th>
			<th>Status</th>
			<th></th>
				<th></th>
				<th></th>
  			</tr>
		</thead>
		<tbody>
        {% for tracker in tracker %}
        <tr> 
            <td>{{ tracker.tracker_name }}</td>
            
            <td>{{ tracker.tracker }}</td>
            <td>{{ tracker.status }}</td>
			
			
            <td style="float: right"> <a href="{% url 'inventory:add_tracker_instance' tracker.id %}"><button type="submit" class="btn btn-warning btn-sm" name="button">Edit</button></a>
             <a href="{% url 'inventory:delete_tracker' tracker.id %}"><button type="submit" class="btn btn-danger btn-sm" name="button">Delete</button></a></td>
            
        </tr>
        {% endfor %}
	</tbody>
    </table>

</div>
{% endblock %}

ATAM/inventory/templates/inventory/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventory</title>
</head>
<body>
    <h1>Asset</h1>
    <table>
        <tr>
            <th>Asset Name</th>
            <th>Assigned Tracker</th>
            <th>Asset Description</th>    
            <th>Created At</th>
        </tr>
        {% for asset in asset %}
        <tr> 
            <td>{{ asset.asset_name }}</td>
            
            <td>{{ asset.assigned_tracker }}</td>
            <td>{{ asset.description }}</td>
            <td>{{ asset.created_at }}</td>
            <td> <a href="{% url 'inventory:add_asset_instance' asset.id %}">[Edit]</a></td>
            <td> <a href="{% url 'inventory:delete_asset' asset.id %}">[Delete]</a></td>
        </tr>
        {% endfor %}
        
    </table>



    <h1>Trcker</h1>
    <table>
        <tr>
            <th>Tracker Name</th>
            <th>Related Asset</th>
            <th>Status</th>    
            
        </tr>
        {% for tracker in tracker %}
        <tr> 
            <td>{{ tracker.tracker_name }}</td>
            
            <td>{{ tracker.tracker }}</td>
            <td>{{ tracker.status }}</td>
            <td> <a href="{% url 'inventory:add_tracker_instance' tracker.id %}">[Edit]</a></td>
            <td> <a href="{% url 'inventory:delete_tracker' tracker.id %}">[Delete]</a></td>
            
        </tr>
        {% endfor %}
        
    </table>
    
    
    
    <a href="{% url 'inventory:add_asset' %}">[Add Asset]</a>
    <a href="{% url 'inventory:add_tracker' %}">[Add Tracker]</a>
 
</body>
</html>