ATAM/ATAM/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),

    path('',include('tracking.urls')),
    path('user/',include('user.urls')),
    path('maintenance/',include('maintenance.urls')),


    #path('',include('tracking.urls')),
    path('tracking/',include('tracking.urls')),
    path('',include('user.urls')),
    path('inventory/',include('inventory.urls')),
    
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ATAM/inventory/urls.py
from django.urls import path
from .views import*
app_name = 'inventory'
urlpatterns = [
    path('',index,name='index'),
    path('add_asset/', add_asset ,name='add_asset'),
    path('add_asset/<int:id>', update_asset ,name='add_asset_instance'),
    path('delete_asset/<int:id>', delete_asset ,name='delete_asset'),
    path('add_tracker/', add_tracker ,name='add_tracker'),
    path('add_tracker/<int:id>', update_tracker ,name='add_tracker_instance'),
    path('delete_tracker/<int:id>', delete_tracker ,name='delete_tracker'),
    path('add_job/', add_job ,name='add_job'),
    path('add_job/<int:id>', update_job ,name='add_job_instance'),
    path('delete_job/<int:id>', delete_job ,name='delete_job'),
    
]

ATAM/maintenance/urls.py
from django.urls import path
from .views import *

app_name = 'maintenance'
urlpatterns = [
    path('',index,name='index'),
    path('<int:tracker_iD>', update_limit ,name='update_limit'),
    # path('<int:tracker_iD>',trackerdetail,name="trackerdetail"),
    path('driver/<int:tracker_iD>',driver,name="driver"),
    path('driver/reset_status/<int:tracker_iD>',reset_status,name="reset_status"),
]

ATAM/tracking/urls.py
from unicodedata import name
from django.urls import path
from .views import*
app_name = 'tracking'
urlpatterns = [
    path('trackers',index,name='index'),
    path("trackers/delete/<int:id>", notification_delete, name="notification_delete"),
    path('current_location/<int:tracker_id>',location_detail,name="current_location"),
    path('tracker/<int:tracker_id>',tracker,name="tracker"),
    path('current_location',location_list,name="current_location_list"),
    path('settings',setting,name="settings"),
    path("notification_alert/", notification_alert, name="notification_alert"),
    path("notification/", notification, name="notification"),
    path('dashboard',dashboard,name="dashboard"),
    path("jobs/", job_list, name="jobs"),
    path('help',help,name="help"),
]

ATAM/tracking/models.py
from operator import mod
from django.db import models

from django.http import JsonResponse
from user.models import User
# Create your models here.




class Asset(models.Model):
    asset_name = models.CharField('Asset name ',max_length=30) 
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    assigned_tracker = models.OneToOneField('Tracker',on_delete=models.CASCADE,verbose_name='Assigned Tracker',blank=True,
        null=True)
    def __str__(self):
        return self.asset_name


class Tracker(models.Model):
    tracker_name = models.CharField('Tracker name ',max_length=30) 
    status_choices = (
        (0,"OFF"),
        (1,"ON"),
    )
    tracker = models.ForeignKey(Asset,on_delete=models.CASCADE,verbose_name='related Asset')
    status = models.IntegerField(default=0,choices=status_choices)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return  self.tracker_name


class Location(models.Model):
    tracker = models.ForeignKey(Tracker,on_delete=models.CASCADE,verbose_name='related tracker')
    lat = models.DecimalField('Tracker latitude value',max_digits=8,decimal_places=4)
    lng = models.DecimalField('Tracker longitude value',max_digits=8,decimal_places=4)

    def __str__(self):
        return  self.tracker.tracker.asset_name


class Job(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='related user')
    tracker = models.ForeignKey(Tracker,on_delete=models.CASCADE,verbose_name='related tracker')
    title = models.CharField('Job Title',max_length=150)
    origin = models.CharField('Job Origin',max_length=150)
    destination = models.CharField('Job Destination',max_length=150)
    description = models.TextField()
    def __str__(self):
        return  self.title

class Notification(models.Model):
    user_sender=models.ForeignKey(User,null=True,blank=True,related_name='user_sender',on_delete=models.CASCADE)
    user_revoker=models.ForeignKey(User,null=True,blank=True,related_name='user_revoker',on_delete=models.CASCADE)
    status=models.CharField(max_length=264,null=True,blank=True,default="unread")
    type_of_notification=models.CharField(max_length=264,null=True,blank=True)

ATAM/tracking/views.py
import json
from multiprocessing import context
from urllib import response
from wsgiref.util import request_uri
from django.shortcuts import render
from .models import *
from django.http import JsonResponse
from django.shortcuts import redirect
#for creating a rest api 
from rest_framework.response import Response
from rest_framework import status, generics
from .serializers import JobSerializer, LocationSerializer
from .models import Location, Job
from rest_framework.parsers import JSONParser
from django.http import JsonResponse
from rest_framework.decorators import api_view   

from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required()
def index(request):
    tracker = Tracker.objects.all()
    return render(request,'tracking/index.html',{"tracker":tracker})


@login_required()
def help(request):
    return render(request,'tracking/help.html')    
@login_required()
def dashboard(request):
    total_users = len(User.objects.all())
    total_trackers = len(Tracker.objects.all())
    total_assets = len(Asset.objects.all())
    jobs = Job.objects.all()
    total_jobs = len(jobs)
    context={
        "total_users":total_users,
        "total_tracker":total_trackers,
        "total_assets":total_assets,
        "total_jobs":total_jobs,
        "jobs":jobs
    }
    return render(request,'tracking/dashboard.html',context)

@login_required()
def setting(request):
    return render(request,'tracking/settings.html')
@login_required()
def notification(request):
    notifications = Notification.objects.values()
    len_notif = Notification.objects.count()
    # for user details
    
    context = {
            'notifications' : notifications, 
            'len_notif' : len_notif,
            }
    return render(request, 'tracking/notification.html', context)
@login_required()
def notification_alert(request):
    return render(request, 'tracking/tracker.html')
@login_required()
def notification_delete(request, id):
    print('-------------------')
    notif_obj = Notification.objects.filter(pk=id)
    print("deleted!",notif_obj)
    notif_obj.delete()
    return redirect('/tracking/notification/')
@login_required()
def tracker(request,tracker_id):
    current_location = Location.objects.filter(tracker=(tracker_id)).values('lat','lng').order_by('-id')[0]
    job = Job.objects.filter(tracker=(tracker_id)).values()
    context = {'current_location':current_location,'job':job}
    #data = current_location|job[0]
    #return JsonResponse(context)
    return render(request,'tracking/tracker.html',context)

@api_view(['GET', 'POST', 'DELETE'])
def location_detail(request,tracker_id):
    """
    Retrieve, update or delete a Location.
    """
    try:
        location = Location.objects.filter(tracker=(tracker_id)).only('lat','lng').order_by('-id')[0]
    except :

        return JsonResponse({"status": "error", "data": "No data found"}, status=status.HTTP_400_BAD_REQUEST)

    if request.method == 'GET':
        serializer = LocationSerializer(location)
        return Response({"status": "success", "data": serializer.data}, status=status.HTTP_200_OK)
    '''May be needed in future'''
    # elif request.method == 'PUT':
    #     data = JSONParser().parse(request)
    #     serializer = LocationSerializer(location, data=data)
    #     #print(serializer)
    #     if serializer.is_valid():
    #         serializer.save()
    #         return JsonResponse(serializer.data)
    #     return JsonResponse(serializer.errors, status=400)

    # elif request.method == 'DELETE':
    #     Location.delete()
    #     return HttpResponse(status=204)

@api_view(['GET', 'POST', 'DELETE'])
def location_list(request):
    """
    Retrieve or post Locations.
    """
    try:
        locations = Location.objects.all()
        
    except :
        #print(location)
        return JsonResponse({"status": "error", "data": "No data found"}, status=status.HTTP_400_BAD_REQUEST)
    
    if request.method == 'GET':
        serializer = LocationSerializer(locations, many=True)
        return Response({"status": "success", "data": serializer.data}, status=status.HTTP_200_OK)
        # 'safe=False' for objects serialization
        
    elif request.method == 'POST':
        location_data = JSONParser().parse(request)
        serializer = LocationSerializer(data=location_data)
        if serializer.is_valid():
            serializer.save()
            return Response({"status": "success", "data": serializer.data}, status=status.HTTP_200_OK)
            
        return Response({"status": "error", "data": serializer.errors}, status=status.HTTP_400_BAD_REQUEST)
    

@api_view(['GET', 'POST'])
def job_list(request):
    """
    Retreive or post tracking jobs
    """
    try:
        jobs = Job.objects.all()
    except:
        return JsonResponse({"status": "error", "data": "No data found"}, status=status.HTTP_400_BAD_REQUEST)

    if request.method == "GET":
        serializer = JobSerializer(jobs, many=True)
        return Response({
            'status' : 'success',
            'data' : serializer.data,
        }, status=status.HTTP_200_OK)
    elif request.method == "POST":
        new_job = JSONParser().parse(request)
        serializer = JobSerializer(data=new_job)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

ATAM/tracking/templates/tracking/ans1.html
<html>
    <head>
        <style>
            p{
                padding: 10px;
                font-size: 1.2em;
            }
            h3
            {
                padding: 10px;
                font-size: 1.5em;
                font-style: italic;
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <h3><a href="{% url 'tracking:help' %}">What is Asset Tracking?</h3></a>
        <p style="float: left;">
        When working on a global platform. There is always a need for a management system that automates your work and allows you to control, manage and monitor various aspects of your organization. There is no proper system to check or track assets that are being utilized in your organization or are in use of particular labour. Similarly, labour tracking is also hard to track. It would be better if the system is automated and live tracking is enabled for both functions. These services include indoor navigation for people, the machinery inside organizations or educational institutions, asset tracking, location of patients inside a hospital. These types of services are also becoming a need of gigantic logistics or warehouse-based companies where there is a need for parcels or vehicle tracking.
        Generating work reports is also a challenging task if there is no proper monitoring on time. So, to cater to this problem, we've brought up a solution in which smart tags will use which will be attached to the asset which will be providing real-time tracking of that particular asset or labour through routers and that router will be providing the data to the server system where the system will be providing the current location of that particular asset.
        </p>
</body>
</html>

ATAM/tracking/templates/tracking/ans2.html
<html>
    <head>
        <style>
            p{
                padding: 10px;
                font-size: 1.2em;
            }
            h3
            {
                padding: 10px;
                font-size: 1.5em;
                font-style: italic;
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <h3><a href="{% url 'tracking:help' %}">What are GPS asset tracking hardware?</h3></a>
        <p style="float: left;">
        ans2
        </p>
</body>
</html>

ATAM/tracking/templates/tracking/ans3.html
<html>
    <head>
        <style>
            p{
                padding: 10px;
                font-size: 1.2em;
            }
            h3
            {
                padding: 10px;
                font-size: 1.5em;
                font-style: italic;
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <h3><a href="{% url 'tracking:help' %}">Technology and stack used for asset tracking system?</h3></a>
        <p style="float: left;">
            answer 3
        </p>
</body>
</html>

ATAM/tracking/templates/tracking/ans4.html
<html>
    <head>
        <style>
            p{
                padding: 10px;
                font-size: 1.2em;
            }
            h3
            {
                padding: 10px;
                font-size: 1.5em;
                font-style: italic;
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <h3><a href="{% url 'tracking:help' %}">What is geofencing?</h3></a>
        <p style="float: left;">
            answer 4
        </p>
</body>
</html>

ATAM/tracking/templates/tracking/ans5.html
<html>
    <head>
        <style>
            p{
                padding: 10px;
                font-size: 1.2em;
            }
            h3
            {
                padding: 10px;
                font-size: 1.5em;
                font-style: italic;
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <h3><a href="{% url 'tracking:help' %}">How does geofencing works with asset tracking?</h3></a>
        <p style="float: left;">
            answer 5
        </p>
</body>
</html>

ATAM/tracking/templates/tracking/ans6.html
<html>
    <head>
        <style>
            p{
                padding: 10px;
                font-size: 1.2em;
            }
            h3
            {
                padding: 10px;
                font-size: 1.5em;
                font-style: italic;
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <h3><a href="{% url 'tracking:help' %}">What is the conclusion & result of the ATAM?</h3></a>
        <p style="float: left;">
            answer 6
        </p>
</body>
</html>

ATAM/tracking/templates/tracking/dashboard.html
{% extends "tracking/layout.html" %}
{% load static %}

{% block title %}Dashboard{% endblock %}

{% block body %}
   <link rel="stylesheet" type="text/css" href="{% static 'tracking/css/styles.css' %}">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="text/javascript" ></script>

  <h3 style="margin-left: 30px;"><strong>Dashboard</strong></h3>
   <div class="container-fluid px-4">
    <div class="row g-3 my-2">
        <div class="col-md-3">
            <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
                <div>
                    <p class="fs-5"><strong>Total Assets</strong><h3 class="fs-2" style="text-align: center">{{total_assets}}</h3></p>
                </div>
                <i class="primary-text bordersecondary-bg p-3">
                    <img src="../tracking/static/tracking/images/icon1.jpg">
                </i>
                
            </div>
        </div>
        <div class="col-md-3">
          <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
              <div>
                  
                  <p class="fs-5"><strong>Total Trackers</strong><h3 class="fs-2" style="text-align: center">{{total_tracker}}</h3></p>
              </div>
              <i class="primary-text bordersecondary-bg p-3">
                <img src="../tracking/static/tracking/images/icon2.jpg">
            </i>
          </div>
      </div>

       <div class="col-md-3">
          <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
              <div>
                  
                  <p class="fs-5"><strong>Total Users</strong><h3 class="fs-2" style="text-align: center">{{total_users}}</h3></p>
              </div>
              <i class="primary-text bordersecondary-bg p-3">
                <img src="../tracking/static/tracking/images/icon3.jpg">
            </i>
          </div>
      </div>
      <div class="col-md-3">
        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
            <div>
                
                <p class="fs-5"><strong>Total Jobs</strong><h3 class="fs-2" style="text-align: center">{{total_jobs}}</h3></p>
            </div>
            <i class="primary-text bordersecondary-bg p-3">
                <img src="../tracking/static/tracking/images/icon4.jpg">
            </i>
        </div>
    </div>
<div class="container" style="margin-top: 30px;">
    <div class="row my-5">
      <h3 class="fs-4 mb-3" style="margin-left: 10px">Recent Jobs</h3>
      <div class="col">
          <table class="table bg-white rounded shadow-sm  table-hover">
            {% for job in jobs %}
              <thead>
                  <tr>
                      <th scope="col" width="50">#</th>
                      <th scope="col">Id</th>
                      <th scope="col">Title</th>
                      <th scope="col">Origin</th>
                      <th scope="col">Destination</th>
                  </tr>
              </thead>
              <tbody>
                  <tr>
                      <th scope="row">{{job.id}}</th>
                      <td>{{job.title}}</td>
                      <td>{{job.origin}}</td>
                      <td>{{job.destination}}</td>
                      <td><a href="{% url 'tracking:tracker' job.tracker.tracker.id %}">
                        View Location</a></td>

              </tbody>
          </table>
      </div>
  </div>
    
 {% endfor %}
 
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        var el = document.getElementById("wrapper");
        var toggleButton = document.getElementById("menu-toggle");

        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
        };
    </script>

  {% endblock %}

ATAM/tracking/templates/tracking/index.html
{% extends "tracking/layout.html" %}
{% load static %}

{% block title %}ATAM{% endblock %}

{% block body %}
<style>
head
{
  float: right;
}
select
{
  float: right;
}
.map
{
 float: right;
}
</style>
<link rel="stylesheet" type="text/css" href="{% static 'tracking/css/styles.css' %}">
                <!-- Page content-->
                <div class="container-fluid">
                  <h3 style="margin-left: 5px;"><strong>Tracking Map</strong></h3>
                  <br>
                  <br>
                    <h3 id="head">Trackers list</h3>
                    <select name="trackers" id="trackers">
                      <option value="main">Trackers</option>
                      <option value="tracker#1">Tracker#1</option>
                      <option value="tracker#2">Tracker#2</option>
                    </select>
                    {% for tracker in tracker%}
                    <li><a href="{% url 'tracking:tracker' tracker.id %}">
                      {{tracker.tracker_name}}</a></li>
                      {% endfor %}
    <!--The div element for the map -->
    <div id="map"></div>
    

    <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
    <div class="map">
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCaMwztN6dbDERbNkKcsBE9NKcu3L27l_A&callback=initialize&libraries=&v=weekly"
      async
    ></script>
  </div>
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script> {% endcomment %}
        
        <!-- Core theme JS-->
        <script src="{% static 'tracking/js/script.js' %}"></script>
    {% endblock %}

ATAM/tracking/templates/tracking/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="text/javascript" ></script> 
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="style.css" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %} {% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <link rel="stylesheet" href="{% static 'tracking/css/main.css' %}">
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <style>
        :root {
  --main-bg-color: #009d63;
  --main-text-color: #009d63;
  --second-text-color: #bbbec5;
  --second-bg-color: #c1efde;
}

.primary-text {
  color: var(--main-text-color);
}

.second-text {
  color: var(--second-text-color);
}

.primary-bg {
  background-color: var(--main-bg-color);
}

.secondary-bg {
  background-color: var(--second-bg-color);
}

.rounded-full {
  border-radius: 100%;
}

#wrapper {
  overflow-x: hidden;
  background-image: linear-gradient(
    to right,
    #baf3d7,
    #c2f5de,
    #cbf7e4,
    #d4f8ea,
    #ddfaef
  );
}

#sidebar-wrapper {
  min-height: 100vh;
  margin-left: -15rem;
  -webkit-transition: margin 0.25s ease-out;
  -moz-transition: margin 0.25s ease-out;
  -o-transition: margin 0.25s ease-out;
  transition: margin 0.25s ease-out;
}

#sidebar-wrapper .sidebar-heading {
  padding: 0.875rem 1.25rem;
  font-size: 1.2rem;
}

#sidebar-wrapper .list-group {
  width: 15rem;
}

#page-content-wrapper {
  min-width: 100vw;
}

#wrapper.toggled #sidebar-wrapper {
  margin-left: 0;
}

#menu-toggle {
  cursor: pointer;
}

.list-group-item {
  border: none;
  padding: 20px 30px;
}

.list-group-item.active {
  background-color: transparent;
  color: var(--main-text-color);
  font-weight: bold;
  border: none;
}

@media (min-width: 768px) {
  #sidebar-wrapper {
    margin-left: 0;
  }

  #page-content-wrapper {
    min-width: 0;
    width: 100%;
  }

  #wrapper.toggled #sidebar-wrapper {
    margin-left: -15rem;
  }
}

    </style>
</head>

<body>
    
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom"><i
                    class="fas fa-user-secret me-2"></i>ATAM System</div>
            <div class="list-group list-group-flush my-3">

                <a href="{% url 'tracking:dashboard' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-tachometer-alt me-2"></i>Dashboard</a>
                <a href="{% url 'tracking:index' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-project-diagram me-2"></i>Asset Tracking</a>
                <a href="{% url 'tracking:notification' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                         class="fas fa-gift me-2"></i>Notifications</a>
                <a href="{% url 'inventory:index' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-chart-line me-2"></i>Inventory</a>
                <a href="{% url 'maintenance:index' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-paperclip me-2"></i>Maintenance Scheduling</a>
                <a href="{% url 'tracking:settings' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-shopping-cart me-2"></i>Settings</a>
                <a href="{% url 'tracking:help' %}" class="list-group-item list-group-item-action bg-transparent second-text fw-bold"><i
                        class="fas fa-power-off me-2"></i>Help Center</a>
            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
              <div class="d-flex align-items-center">
                  <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
                  <h2 class="fs-2 m-0">Currently Viewing</h2>
              </div>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle second-text fw-bold" href="#" id="navbarDropdown"
                              role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              <i class="fas fa-user me-2"></i>{{ request.user.username}}
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                          </ul>
                      </li>
                  </ul>
              </div>
          </nav>
            <!-- Page content-->
            {% block body %}
            <!-- include body content here for html page -->
            {% endblock %}
        </div>
    </div>
</body>

</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript"></script>

<script>
    $(document).ready(function () {
        $("#logout").click(function () {
            var user_token = window.localStorage.getItem("token");
            console.log(user_token);
            $.ajax({
                type: "POST",
                headers: {
                    Authorization: "Token " + user_token,
                    "Content-Type": "application/json",
                },

                url: "http://ec2-35-89-78-206.us-west-2.compute.amazonaws.com:8000/user/api/logout/",

                success: function (response) {
                    console.log(response);
                },
                error: function (XHR, status, err) {
                    console.log("Error!");
                },
            });
        });
    });
</script>
<script src="{% static 'tracking/js/notification_alerts.js' %}"></script>

ATAM/tracking/templates/tracking/notification.html
{% extends "tracking/layout.html" %}
{% load static %}

{% block title %}Notifications{% endblock %}

{% block body %}

<link rel="stylesheet" type="text/css" href="{% static 'tracking/css/styles.css' %}">
{% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> {% endcomment %}
{% comment %} <link rel="stylesheet" href="{% static 'bootstrap513/css/bootstrap.css' %}"> {% endcomment %}
<div>
    <h3 style="margin-left: 30px;"><strong>Notifications</strong></h3>
    <table id="notification_table" class="table">
        <thead>
            <tr>
                <th scope="col">User Sender</th>
                <th scope="col">User Revoker</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody id="old_tbody">
            
            {% for var in notifications %}
            <tr>
                {% comment %} <td>{{ user_details }}</td> {% endcomment %}
                <td>{{ var.id }}</td>
                <td>{{ var.status }}</td>
                <td>{{ var.type_of_notification }}</td>
                <td>
                    <a href="{% url 'tracking:notification_delete' var.id %}">
                        <button type="submit" class="btn btn-danger btn-sm">
                            Mark as Read
                        </button>
                    </a>
                </td>
            </tr>
                {% comment %} <h1>{{ var.type_of_notification }}</h1> {% endcomment %}
            {% endfor %}
            
        </tbody>
    </table>
</div>


{% endblock body %}