ATAM/ATAM/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),

    path('',include('tracking.urls')),
    path('user/',include('user.urls')),
    path('maintenance/',include('maintenance.urls')),


    #path('',include('tracking.urls')),
    path('tracking/',include('tracking.urls')),
    path('',include('user.urls')),
    path('inventory/',include('inventory.urls')),
    
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ATAM/maintenance/urls.py
from django.urls import path
from .views import *

app_name = 'maintenance'
urlpatterns = [
    path('',index,name='index'),
    path('<int:tracker_iD>', update_limit ,name='update_limit'),
    # path('<int:tracker_iD>',trackerdetail,name="trackerdetail"),
    path('driver/<int:tracker_iD>',driver,name="driver"),
    path('driver/reset_status/<int:tracker_iD>',reset_status,name="reset_status"),
]

ATAM/maintenance/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from tracking.models import *

# Create your models here.
class Maintenance(models.Model):
    # tracker = models.ForeignKey(Tracker,on_delete=models.CASCADE,verbose_name='related tracker')
    tracker = models.IntegerField()
    total_distance = models.DecimalField('Total Distance Covered',max_digits=8,decimal_places=4)
    description = models.CharField(default="NO MAINTENANCE SCHEDULE",max_length=100)
    maintenance_status = models.CharField(default="Not Pending", max_length=15)
    maintenance_limit = models.IntegerField(default=20, validators=[ MaxValueValidator(100), MinValueValidator(20)])
    def __int__(self):
        return  self.tracker

ATAM/maintenance/forms.py
from django import forms
from maintenance.models import Maintenance

class AddMaintenanceForm(forms.ModelForm):
    class Meta:
        model = Maintenance
        fields = ['maintenance_limit']

class UpdateMaintenanceForm(forms.ModelForm):
    class Meta:
        model = Maintenance
        fields = ['maintenance_status']

ATAM/maintenance/views.py
from django.shortcuts import render
from tracking.models import Location
from haversine import haversine
import time
from .models import *
from .forms import *
from django.shortcuts import redirect

# Create your views here.

def trackers_list():
    # get all values of column tracker from maintenance table
    rows = list(Maintenance.objects.values_list("tracker"))

    # filter unique tracker ids
    trackerids = list(set([list(id)[0] for id in rows]))
    return trackerids

# get latest maintenace details of all trackers from maintenance table
def maintenance_detail():
    trackerids = trackers_list()
    details = []

    asset_names = []
    for trackerid in trackerids:
        details.append(Maintenance.objects.filter(tracker=trackerid).order_by("-id")[0])
        asset_names.append(Location.objects.filter(tracker_id=trackerid)[0])
    return details, asset_names

def index(request):
    details = maintenance_detail()[0]
    asset_names = maintenance_detail()[1]
    return render(request, 'maintenance/index.html', {
        "locations": details,
        "names": asset_names

    })


# def total_distance(tracker_iD):
#     locations = Location.objects.filter(tracker_id=tracker_iD)
#     list_locations = list(locations)
#     # distances = []
#     asset_name = ''
#     # tracker_id = list_locations[0].tracker_id
#     msg = 'NO MAINTENACE SCHEDULE'
#     d = 0
#     for i in range(len(list_locations)-1):
#         point1 = (list_locations[i].lat, list_locations[i].lng)
#         point2 = (list_locations[i+1].lat, list_locations[i+1].lng)
#         # distance = haversine(point1, point2)
#         diff = 0.5422548807007272
#         distance = diff * haversine(point1, point2) + haversine(point1, point2)
#         # distances.append([distance, point1, point2, list_locations[i]])
#         asset_name = list_locations[i]
#         # asset_id = list_locations[i]
#         d += distance
#         if (d / 20) >= 1:
#             msg = 'CHANGE OIL'
#             break
#         else:
#             msg = 'NO MAINTENACE SCHEDULE'
#     output = [d, msg, asset_name]
#     return output


def driver(request, tracker_iD):
    try:
        maintenance = Maintenance.objects.filter(tracker=tracker_iD).order_by("-id")[0]
    except IndexError:
        # get all values of column tracker from location table
        rows = list(Location.objects.values_list("tracker"))

        # filter unique tracker ids
        trackerids = list(set([list(id)[0] for id in rows]))
        if tracker_iD in trackerids:
            maintenance = Maintenance.objects.create(tracker = tracker_iD, total_distance = 0)
        else:
            return redirect(f'/maintenance')

    locations = Location.objects.filter(tracker_id=tracker_iD)
    list_locations = list(locations)
    # distances = []
    asset_name = list_locations[0]
    tracker_id = list_locations[0].tracker_id
    msg = 'NO MAINTENACE SCHEDULE'
    d = 0
    for i in range(len(list_locations)-1):
        point1 = (list_locations[i].lat, list_locations[i].lng)
        point2 = (list_locations[i+1].lat, list_locations[i+1].lng)
        # distance = haversine(point1, point2)
        diff = 0.5422548807007272
        distance = diff * haversine(point1, point2) + haversine(point1, point2)
        # distances.append([distance, point1, point2, list_locations[i]])
        # asset_name = list_locations[i]
        # asset_id = list_locations[i]
        d += distance
        if (d / maintenance.maintenance_limit) >= 1:
            msg = 'CHANGE OIL'
            # break
        else:
            msg = 'NO MAINTENACE SCHEDULE'
    # Add record only if total_distance changes
    # output = total_distance(tracker_iD)
    # d = output[0]
    # msg = output[1]
    # asset_name = output[2]
    try:
        prev_entry = Maintenance.objects.filter(tracker=tracker_iD).order_by("-id")[0]
        prev_entry_distance = float(prev_entry.total_distance)
        if round(d,4) != prev_entry_distance:
            # if round(d,4) >= prev_entry.maintenance_limit:
            #     new_entry = Maintenance.objects.create(tracker = tracker_iD, total_distance = d, description = msg, maintenance_status = "Pending")
            # else:
            #     new_entry = Maintenance.objects.create(tracker = tracker_iD, total_distance = d, description = msg)
            new_entry = Maintenance.objects.create(tracker = tracker_iD, total_distance = d, description = msg)
            if round(d,4) >= new_entry.maintenance_limit:
                new_entry.maintenance_status = "Pending"
                new_entry.save()
            else:
                new_entry.save()
    except:
        # if float(prev_entry.total_distance) >= prev_entry.maintenance_limit:
        #         new_entry = Maintenance.objects.create(tracker = tracker_iD, total_distance = d, description = msg, maintenance_status = "Pending")
        # else:
        new_entry = Maintenance.objects.create(tracker = tracker_iD, total_distance = d, description = msg)
        new_entry.save()

    return render(request,'maintenance/driver.html',{
        "name": asset_name,
        "alert": msg,
        "distance": round(d,4),
        "trackerid": tracker_id
    })

# def trackerdetail(request, tracker_iD):
#     details = total_distance(tracker_iD)

#     distance = details[0]
#     asset_name = details[2]

#     return render(request,'maintenance/trackerdetail.html',{
#         "distance": distance,
#         "name": asset_name
#     })


# Update maintenance_limit


# def add_limit(request):
#     form = AddMaintenanceForm()
#     if request.method == 'POST':
#         form = AddMaintenanceForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('/maintenance/')
#     else:

#         context = {
#             'form':form
#         }
#         return render(request,'maintenance/update_limit.html',context)


def update_limit(request,tracker_iD):
    asset = Maintenance.objects.filter(tracker=tracker_iD).order_by("-id")[0]
    # asset_id = asset.id
    # asset = Maintenance.objects.get(id=asset_id)
    if request.method == 'POST':
        form = AddMaintenanceForm(request.POST, instance=asset)
        if float(asset.total_distance) >= asset.maintenance_limit:
            asset.maintenance_status = "Pending"
            asset.description = "CHANGE OIL"

        else:
            asset.maintenance_status = "Not Pending"
            asset.description = "NO MAINTENACE SCHEDULE"

        if form.is_valid():
            form.save()
            return redirect('/maintenance/')
        
    else:
        form = AddMaintenanceForm(instance=asset)

    return render(request, 'maintenance/update_limit.html', {'form': form}) 


def reset_status(request,tracker_iD):
    asset = Maintenance.objects.filter(tracker=tracker_iD).order_by("-id")[0]
    # make another entry in location table of same position to make total distance zero
    prev_loc = Location.objects.filter(tracker=tracker_iD).order_by("-id")[0]
    # if request.method == 'POST':
        # form = UpdateMaintenanceForm(request.POST, instance=asset)
    asset.maintenance_status = "Done"
    asset.description = "NO MAINTENACE SCHEDULE"
    asset.total_distance = 0
        # if form.is_valid():
            # form.save()
    asset.save()
    print("Asset = ", asset)
    new_location = Location.objects.create(lat = float(prev_loc.lat), lng = float(prev_loc.lng), tracker_id = prev_loc.tracker_id)
    new_location.save()

    return redirect(f'/maintenance')
    # else:

        # return redirect('/maintenance/')

ATAM/maintenance/templates/maintenance/driver.html
{% extends "tracking/layout.html" %} 
{% load static %} 
{% block title %}
Maintenance-{{name}}
{% endblock %}

{% block body %}
<link rel="stylesheet" type="text/css" href="{% static 'tracking/css/styles.css' %}">
<div>
    <h1>{{ name }}</h1>
    <!-- <ul>
        {% for distance in distances %}
        <li>
          distance from point {{ distance.1 }} to point {{ distance.2 }} = {{ distance.0 }} km
        </li> -->
        <!-- <li>
            <!-- gives car/truck -->
            <!-- {{location}} -->
        <!-- </li> -->
  
        <!-- {% endfor %} -->
        <!-- <li>{{ locations.0.lat }}</li>
        <li>{{ locations.1.lat }}</li>
        <li>{{ locations.2.lat }}</li> -->

      <!-- </ul> -->
      <br><br>
      <p>Maintenance Status =  {{ alert }}</p>
      <!-- <p>Distance Covered in Total = {{ distance }} km</p> -->
      {% if alert == "CHANGE OIL" %}
      <!-- <form method="post"> -->
        <!-- {% csrf_token %} -->
        <!-- <input type="button" value="Pending"> -->
        <a href="{% url 'maintenance:reset_status' trackerid %}"><button type="submit">Done</button></a>
        
        <!-- </form> -->
        
        {% endif %}
        <!-- <a href="{% url 'maintenance:reset_status' trackerid %}"><button type="submit">Done</button></a> -->
</div>


<script>

</script>
{% endblock %}

ATAM/maintenance/templates/maintenance/index.html
{% extends "tracking/layout.html" %} 
{% load static %} 
{% block title %}
Maintenace 
{% endblock %}

{% block body %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'tracking/css/styles.css' %}">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div>
    <h1>Locations</h1>
    <table class="table table-warning table-hover">
      <thead>
      <tr>
        <th scope="col">Asset Name</th>
        <th scope="col">Tracker id</th>
        <th scope="col">Total Distance Covered(km)</th>
        <th scope="col">Maintenance Status</th>
        <th scope="col">Maintenance Limit</th>
        <th scope="col">Change Limit</th>
      </tr>
    </thead>
    <tbody>
      {% for location in locations %}
      <tr>
        {% for name in names %}
          {% if name.tracker_id == location.tracker %}
            <td>{{ name }}</td>
          {% endif %}
        {% endfor %}
        <td>{{ location.tracker }}</td>
        <td>{{ location.total_distance }}</td>
        <td>{{ location.maintenance_status }}</td>
        <td>{{ location.maintenance_limit }}</td>
        <!-- <td><button>Change</button></td> -->
        <td><a href="{% url 'maintenance:update_limit' location.tracker %}"><button type="submit" class="btn btn-warning">Change</button></a></td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
    <!-- <ul>
      {% for location in locations %}
      <li>
        Location {{ location.id }}: {{ location.total_distance }} : {{ location.maintenance_status }}
        : {{ location.tracker }} : {{ location.maintenance_limit }}
        <button>Edit</button>
      </li>

      {% endfor %}
    </ul> -->
  </div>
{% endblock %}

ATAM/maintenance/templates/maintenance/trackerdetail.html
{% extends "tracking/layout.html" %} 
{% load static %} 
{% block title %}
Maintenance-{{name}}
{% endblock %}


{% block body %}
<link rel="stylesheet" type="text/css" href="{% static 'tracking/css/styles.css' %}">
<div>
    <h1>{{ name }}</h1>
    <br><br>
    <p>Distance Covered in Total = {{ distance }} km</p>
</div>

{% endblock %}

ATAM/maintenance/templates/maintenance/update_limit.html
{% extends "tracking/layout.html" %} 
{% load static %} 
{% block title %}
Maintenance Limit Updation
{% endblock %}

{% block body %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'tracking/css/styles.css' %}">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


{% load crispy_forms_tags %}  
<body>
    <h3>
        Update Maintenace Limit
    </h3>
    <form method="post">
        {% csrf_token %}
        <div class="md-form form-group w-50">{{ form.maintenance_limit|as_crispy_field }}</div>
        <input type="submit" value="Update Limit">
    </form>

{% endblock %}